version: '3'
services:
  web:
    container_name: todo_app
    build:
      context: ./src/todo-app
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src/todo-app:/var/www/html
    command: > 
      sh -c "apache2-foreground"  
    depends_on:
      - db
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_db
      MYSQL_USER: task_user
      MYSQL_PASSWORD: root
    volumes:
      - ./task-data:/var/lib/mysql
    ports:
     - '3306:3306'
volumes:
  task-data:

